### ISSUE TITLE
サービスが死んでる

### ISSUE THREAD

**Issue by shari-sushi** [shari-sushi/V-Kara-Lists#259]
- 09:00 apiサーバーダウン
- 18時頃発覚→即復旧
- 翌日、フロントダウン発覚
  - 復旧せず…
 
---
過去コミットローラー作戦。
```
⑤ a9db1b1 (HEAD -> app_multi_stage_build) appのマルチステービルド化(失敗？)
④ 21f9a3a node アプデ
③ 7ce4764 (origin/develop, origin/HEAD, improve/user_form, develop) Merge pull request #251 from shari-sushi/improve/user_form
　6bce849 (origin/improve/user_form) エラーモーダル外観調整
② cc79204 微調整：見た目やvalit errorメッセージ、validateそのもの
　15a03ca Merge pull request #247 from shari-sushi/api_multi_stage_build
　8e65576 (origin/api_multi_stage_build) build日時メモ、dockerfileコメント編集
　61fbb33 feat: Makefileのファイル名前修正、環境確認用のsample env追加、env取得できなくてもapi起動するように
　fb62ac7 feat: apiのmulti-stage build化
　d061591 Merge pull request #242 from shari-sushi/216-v2_resourse
　2e8f5b0 余計な物の削除
　f260556 ルーティング再調整
　58888e5 (origin/v2) routingにv2作成、interface/handlerをv1, v2作ってv2に丸コピ
　10341f9 Merge pull request #217 from shari-sushi/feature-215-login
① 193c254 (origin/feature-215-login) fix ログインできるように修正
```

**Comment by shari-sushi** [comment]
### 10/23 4:15 ①で復旧成功
```
commit 10341f997654939d98e1096eae6daa68f9f9380e (HEAD)
サービスにログインできない問題を修正
(最新branchだと`Merge pull request #217 from shari-sushi/feature-215-login に該当するみたい`)
```

---
AWSのログでlocalhostとのこと。…？
 ```
2024年10月23日 04:09 (UTC+9:00) - Local: http://localhost:80
2024年10月23日 04:09 (UTC+9:00) ✓ Ready in 1358ms
2024年10月23日 04:09 (UTC+9:00) ▲ Next.js 13.5.6
2024年10月23日 04:09 (UTC+9:00) > next start -p 80
```
```js
export const domain = process.env.NODE_ENV === 'development' ? {
  // VSCode上
  backendHost: 'http://localhost:8080/v1'
} : {
  // クラウド環境
  backendHost: 'https://backend.v-karaoke.com/v1'
}
```
↓ここだけ変更。(もともとのrun dev では起動しなかったので)
```docker
FROM node:18-alpine
WORKDIR /app/src 
COPY ./myapp .
RUN npm install
RUN npm run build
EXPOSE 80
CMD ["npm", "run", "start"]
```
```js
  "scripts": {
    "dev": "next dev -p 80",
    "start": "next start -p 80",
```
ターゲットグループのターゲットport 80

### 最新commitだと、port 80はaccess deniedって弾かれてた気がするので、フロントのコードでいじっちゃいけないとこいじった…？
---

**Comment by shari-sushi** [comment]
### 10/23 04:34 ②デプロイ更新成功
cc79204 微調整：見た目やvalit errorメッセージ、validateそのもの

evt.ts, Dockerfile, package.jsonについて↑と同じ
Dockerfileはここもrun devになっていたのでbuild, startに修正
(変化が分かるようにフロントの文字列のみ調整)

やっぱlocalhostのログ出る。紛らわしいな…。
ちなみに、自分のコード上にlocalhostの単語が無くてもこのログになる。
```
- Local: http://localhost:80
```

**Comment by shari-sushi** [comment]
### 10/23 ③：デプロイ成功
```
cc79204 微調整：見た目やvalit errorメッセージ、validateそのもの
```

↑に同じ。

**Comment by shari-sushi** [comment]
### 10/23 ④：デプロイ成功
```
21f9a3a node アプデ
```

↑に同じ。ちなみに
    "node": "^20.16.0",
    "nookies": "^2.5.2",
 になった。
 のと同時に、package.jsonの構造が変わってた。
このcommitで↓が丸っと追加されたみたい。これのせいかと思ったら違うみたい。
 ```js
     "node_modules/node": {
      "version": "20.16.0",
      "resolved": "https://registry.npmjs.org/node/-/node-20.16.0.tgz",
      "integrity": "sha512-NNbwzbXNi1MBoLYZAKVig2ICuCH6Wueke3zrsldpjtrSkL6QqBDhiZeBFOi19mj9kxeEPKldjHfem0rnK8OKrw==",
      "hasInstallScript": true,
      "license": "ISC",
      "dependencies": {
        "node-bin-setup": "^1.0.0"
      },
      "bin": {
        "node": "bin/node"
      },
      "engines": {
        "npm": ">=5.0.0"
      }
    },
    "node_modules/node-bin-setup": {
      "version": "1.1.3",
      "resolved": "https://registry.npmjs.org/node-bin-setup/-/node-bin-setup-1.1.3.tgz",
      "integrity": "sha512-opgw9iSCAzT2+6wJOETCpeRYAQxSopqQ2z+N6BXwIMsQQ7Zj5M8MaafQY8JMlolRR6R1UXg2WmhKp0p9lSOivg==",
      "license": "ISC"
    },
```

**Comment by shari-sushi** [comment]
## 10/26 4:56 ⑤：デプロイ更新失敗
```
a9db1b1 (HEAD -> app_multi_stage_build) appのマルチステービルド化(失敗？)
```

この復旧作業ではここからマルチステージビルド
(buildまではできた。正しいか不明だけど)
ここで初めてサーバー落ち再現
やっぱaccess deniedか…
```
2024年10月23日 04:57 (UTC+9:00) | Error: listen EACCES: permission denied 10.1.0.79:80
2024年10月23日 04:57 (UTC+9:00) | at Server.setupListenHandle [as _listen2] (node:net:1800:21)
2024年10月23日 04:57 (UTC+9:00) | at listenInCluster (node:net:1865:12)
2024年10月23日 04:57 (UTC+9:00) | at GetAddrInfoReqWrap.doListen [as callback] (node:net:2014:7)
2024年10月23日 04:57 (UTC+9:00) | at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8) { 
2024年10月23日 04:57 (UTC+9:00) | code: 'EACCES', 
2024年10月23日 04:57 (UTC+9:00) | errno: -13,
2024年10月23日 04:57 (UTC+9:00) | syscall: 'listen',
2024年10月23日 04:57 (UTC+9:00) | address: '10.1.0.79',
2024年10月23日 04:57 (UTC+9:00) | port: 80
2024年10月23日 04:57 (UTC+9:00) | } 
2024年10月23日 04:57 (UTC+9:00) | ⨯ Failed to start server
```

### これってport80だからなのかな？無関係に権限が無いのかな？

**Comment by shari-sushi** [comment]
### ↑の検証
ローカルにて、docker runしたところ起動したがアクセスはできず。
```shell
/t0016Next$ docker run v-kara-list-app02:latest
  ▲ Next.js 13.5.6
  - Local:        http://localhost:80
  - Network:      http://0.0.0.0:80

 ✓ Ready in 63ms
```
ブラウザにて、`このサイトにアクセスできませんlocalhost で接続が拒否されました。`

ローカルにてnpm run devしたところ、サーバー起動せず。
```bash
/t0016Next/myapp$ npm run dev

> 0016api@0.1.0 dev
> next dev -p 80

 ⨯ Failed to start server
Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (node:net:1882:21)
    at listenInCluster (node:net:1961:12)
    at Server.listen (node:net:2063:7)
    at /home/hoge_hoge/t0016Next/myapp/node_modules/next/dist/server/lib/start-server.js:254:16
    at new Promise (<anonymous>)
    at startServer (/home/hoge_hoge/t0016Next/myapp/node_modules/next/dist/server/lib/start-server.js:191:11)
    at process.<anonymous> (/home/hoge_hoge/t0016Next/myapp/node_modules/next/dist/server/lib/start-server.js:277:19)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
```

**Comment by shari-sushi** [comment]
```
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs
```
この部分で非rootユーザーを作ってるからport80の権限が不足してるみたい。
Cloude 3 君はセキュリティ的には1024以上を指定した方が良いというが、ソース不明。聞き直したら、非root user推奨なだけで、port番号の推奨非推奨のソースは見つからなかったとのこと。
今更awsのターゲットグループ変更するのめんどいしこのままでいいか。

でも、てか3000より80の方が上位の権限が必要 = 危険なのはそうなのかな？

**Comment by shari-sushi** [comment]
3005にしてdockerのportに割り当てしたらできた。
` docker run -p 3005:3005 v-kara-list-app02:latest`
```
$ docker run v-kara-list-app02
  ▲ Next.js 13.5.6
  - Local:        http://localhost:3005
  - Network:      http://0.0.0.0:3005

 ✓ Ready in 63ms
 ```
 ※割り当てないと80のと同じで、ブラウザ上では`このサイトにアクセスできません…`
 
 
 run devなら今回は起動したしアクセスできた。
 ```
 $ npm run dev

> 0016api@0.1.0 dev
> next dev -p 3005

  ▲ Next.js 13.5.6
  - Local:        http://localhost:3005

 ✓ Ready in 1528ms
 ✓ Compiled / in 1921ms (428 modules)
pageName, sessionToken, isSigni = Top undefined false
```

**Comment by shari-sushi** [comment]
あー…
80のままでも割り当てたらできたわどういうこと…
```
$ docker run -p 80:80 v-kara-list-app02:latest
  ▲ Next.js 13.5.6
  - Local:        http://localhost:80
  - Network:      http://0.0.0.0:80

 ✓ Ready in 45ms
pageName, sessionToken, isSigni = Top undefined false
```
